In [1]:
import json
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
from pathlib import Path
from collections.abc import Mapping
from IPython.display import display
from plotting_utils import (
    get_nice_prompt_name,
    get_short_model_name,
    extract_prompt_version,
)

In [2]:
# This is where we'll want to add something like "Structured rules"
PROMPT_MAPPING = {
    "Accuracy-ChildBenefit-structuredOutput-v2.md": "Rules in URLs",
    "Accuracy-ChildBenefit-structuredOutput-v2.1_no_links.md": "Training data only",
    "Accuracy-ChildBenefit-structuredOutput-v2.2_no_links_rules_in_prompt.md": "Rules in prompt",
    "StructuredSpecification-ChildBenefit-v1.md": "Rules provided in form of Structured Specification"
}

In [3]:
def create_df_runs(
    test_cohort: str = "child_benefit", drop_unknown_prompt: bool = True
) -> pd.DataFrame:
    reports_dir = Path(f"testOutputs/{test_cohort}/eval_reports")
    run_data = []
    for run_dir in reports_dir.iterdir():
        if not run_dir.is_dir():
            continue

        summary_path = run_dir / "evaluation_report_summary.json"
        cases_path = run_dir / "evaluation_report_cases.json"

        if summary_path.exists() and cases_path.exists():
            with open(summary_path, "r") as f:
                summary = json.load(f)
            with open(cases_path, "r") as f:
                cases = json.load(f)

            config = summary.get("run_config", {})

            run_data.append(
                {
                    "run_name": run_dir.name,
                    "model": config.get("eligibility_model_string", "unknown"),
                    "prompt": config.get("eligibility_prompt", "unknown"),
                    "url_allowed": config.get("url_tool_call_allowed", True),
                    "commit": config.get("commit", "unknown"),
                    "results": cases.get(
                        "results", cases
                    ),  # Handles nested (old style) or flat cases dict
                }
            )

    df_runs = pd.DataFrame(run_data)

    # From before we recorded the prompt in this way and have different shaped output
    if drop_unknown_prompt:
        df_runs = (df_runs[df_runs["prompt"] != "unknown"]).reset_index()

    # Create some slightly shorter/nicer names for plotting/tables
    df_runs[["prompt_name", "prompt_type"]] = (
        df_runs["prompt"]
        .apply(lambda p: get_nice_prompt_name(p, PROMPT_MAPPING))
        .apply(pd.Series)
    )
    df_runs["model_name"] = df_runs["model"].apply(get_short_model_name)

    df_runs["config_key"] = df_runs.apply(
        lambda x: (x["model_name"], x["prompt_name"], x["url_allowed"]), axis=1
    )

    df_runs["prompt_version"] = df_runs["prompt_name"].apply(extract_prompt_version)

    # Can't plot full prompt name - it breaks the axes
    df_runs["config_label"] = (
        df_runs["model_name"]
        + " | "
        + df_runs["prompt_type"]
        + " | "
        + df_runs["url_allowed"].map({True: "URLs ON", False: "URLs OFF"})
    )
    print("df_runs created and its head looks like this:")
    display(df_runs.head())

    print("Configurations found and their run counts:")
    display(df_runs["config_key"].value_counts().to_frame("Count"))

    return df_runs


df_runs = create_df_runs(drop_unknown_prompt=False)

df_runs created and its head looks like this:

,run_name,model,prompt,url_allowed,commit,results,prompt_name,prompt_type,model_name,config_key,prompt_version,config_label
0,2026-03-04T08:55:32.859368__RepoCommit=3890395,unknown,unknown,True,unknown,{'MULTI_MIXED_THREE_MIXED': {'case_id': 'MULTI...,unknown,Other Prompt,unknown,"(unknown, unknown, True)",v?,unknown | Other Prompt | URLs ON
1,2026-03-10T17:14:15.475988__Model=claude-sonne...,bedrock/converse/eu.anthropic.claude-sonnet-4-...,agents/TechnicalHypotheses/Accuracy-ChildBenef...,True,9fc029f,{'MULTI_MIXED_THREE_MIXED': {'case_id': 'MULTI...,Accuracy-ChildBenefit-structuredOutput-v2.md,Rules in URLs,claude-sonnet-4-5,"(claude-sonnet-4-5, Accuracy-ChildBenefit-stru...",v2,claude-sonnet-4-5 | Rules in URLs | URLs ON
2,2026-03-04T20:18:49.825618__Model=claude-sonne...,bedrock/converse/eu.anthropic.claude-sonnet-4-...,agents/TechnicalHypotheses/Accuracy-ChildBenef...,True,4ce9578,{'MULTI_MIXED_THREE_MIXED': {'case_id': 'MULTI...,Accuracy-ChildBenefit-structuredOutput-v2.md,Rules in URLs,claude-sonnet-4-5,"(claude-sonnet-4-5, Accuracy-ChildBenefit-stru...",v2,claude-sonnet-4-5 | Rules in URLs | URLs ON
3,2026-03-04T17:22:27.476356__Model=claude-sonne...,bedrock/converse/eu.anthropic.claude-sonnet-4-...,agents/TechnicalHypotheses/Accuracy-ChildBenef...,True,unknown,{'MULTI_MIXED_THREE_MIXED': {'case_id': 'MULTI...,Accuracy-ChildBenefit-structuredOutput-v2.md,Rules in URLs,claude-sonnet-4-5,"(claude-sonnet-4-5, Accuracy-ChildBenefit-stru...",v2,claude-sonnet-4-5 | Rules in URLs | URLs ON
4,2026-03-04T19:06:24.738962__Model=claude-sonne...,bedrock/converse/eu.anthropic.claude-sonnet-4-...,agents/TechnicalHypotheses/Accuracy-ChildBenef...,False,4ce9578,{'MULTI_MIXED_THREE_MIXED': {'case_id': 'MULTI...,Accuracy-ChildBenefit-structuredOutput-v2.1_no...,Training data only,claude-sonnet-4-5,"(claude-sonnet-4-5, Accuracy-ChildBenefit-stru...",v2.1,claude-sonnet-4-5 | Training data only | URLs OFF

Configurations found and their run counts:

                                                    Count
config_key
(claude-sonnet-4-5, Accuracy-ChildBenefit-struc...      6
(unknown, unknown, True)                                1
(claude-sonnet-4-5, Accuracy-ChildBenefit-struc...      1

In [4]:
df_runs.columns

Index(['run_name', 'model', 'prompt', 'url_allowed', 'commit', 'results',
       'prompt_name', 'prompt_type', 'model_name', 'config_key',
       'prompt_version', 'config_label'],
      dtype='object')

In [5]:
df_runs['prompt_name'].value_counts()

prompt_name
Accuracy-ChildBenefit-structuredOutput-v2.md               6
unknown                                                    1
Accuracy-ChildBenefit-structuredOutput-v2.1_no_links.md    1
Name: count, dtype: int64

In [6]:
# analysis/testOutputs/child_benefit/2026-03-09T17:22:56.608315__Model=claude-sonnet-4-5__Commit=530924b has inconsistent tool calls, 
# dig into data to see how inconsistent
%pdb off

import json
from pathlib import Path

import pandas as pd


paths = Path("testOutputs/child_benefit/2026-03-09T17:22:56.608315__Model=claude-sonnet-4-5__Commit=530924b").glob("Permutation*.conversation.json")
#print(list(paths))
dfs = []
for p in paths:
    with p.open('r') as f:
        payload = json.load(f)
        df = pd.json_normalize(payload)
        dfs.append(df)

#dfs = [pd.read_json(pd.json_normalize(''.join(p.open().readlines())) for p in paths]
df = pd.concat(dfs)

Automatic pdb calling has been turned OFF

In [7]:
df.columns

Index(['case_id', 'conversation', 'tool_activity', 'meta.permutation',
       'meta.test_case.case_id',
       'meta.test_case.facts.claimant_lives_in_uk.description',
       'meta.test_case.facts.claimant_lives_in_uk.value',
       'meta.test_case.facts.children.description',
       'meta.test_case.facts.children.value', 'meta.test_case.agent_script',
       'meta.test_case.expected_eligibility', 'meta.execution_datetime',
       'meta.run_config.actor_model_string', 'meta.run_config.test_cohort',
       'meta.run_config.commit', 'meta.run_config.hypothesis_name',
       'meta.run_config.eligibility_model_string',
       'meta.run_config.actor_prompt', 'meta.run_config.eligibility_prompt',
       'meta.run_config.test_set_size',
       'meta.run_config.url_tool_call_allowed', 'usage.total_prompt_tokens',
       'usage.total_completion_tokens', 'usage.total_overall_tokens',
       'usage.breakdown_by_agent.child_benefit_eligibility_agent.prompt_tokens',
       'usage.breakdown_by_agent.child_benefit_eligibility_agent.completion_tokens',
       'usage.breakdown_by_agent.child_benefit_eligibility_agent.total',
       'usage.breakdown_by_agent.actor.prompt_tokens',
       'usage.breakdown_by_agent.actor.completion_tokens',
       'usage.breakdown_by_agent.actor.total', 'performance.duration_seconds',
       'child_benefit_eligibility_agent_payload.response.will_continue',
       'child_benefit_eligibility_agent_payload.response.scheduling',
       'child_benefit_eligibility_agent_payload.response.parts',
       'child_benefit_eligibility_agent_payload.response.id',
       'child_benefit_eligibility_agent_payload.response.name',
       'child_benefit_eligibility_agent_payload.response.response.child_evaluations',
       'child_benefit_eligibility_agent_payload.response.response.overall_reasoning'],
      dtype='object')

In [8]:
no_answer_df = df[df["child_benefit_eligibility_agent_payload.response.id"].isna() == True]

In [9]:
import pyarrow as pa
new_type = pd.ArrowDtype(
    pa.list_(
        pa.struct(
            fields=[
                ('author', pa.string()),
                ('text', pa.string()),
                ('timestamp', pa.string())
            ]
        )
    )
)
no_answer_df["conversation"] = no_answer_df["conversation"].astype(new_type)

no_answer_df["conversation"].to_list()

/var/folders/b2/7k_brtrs25x6v118yqs3yt8m0000gp/T/ipykernel_60275/3036625412.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_answer_df["conversation"] = no_answer_df["conversation"].astype(new_type)

[[{'author': 'child_benefit_eligibility_agent',
   'text': "Hello! I'd be happy to help you determine if you're eligible for Child Benefit in the UK.\n\nTo assess your eligibility, I'll need to ask you some questions about your circumstances and the child or children you're inquiring about.\n\nLet me start with a few basic questions:\n\n1. **Do you have a child or children you're responsible for?** If yes, how many children are you asking about, and what are their ages?\n\nOnce I know this, I can ask more specific questions to determine your eligibility for each child.",
   'timestamp': '2026-03-09T17:23:49.647066'},
  {'author': 'actor',
   'text': "Hi! Yes, I have one child I'm asking about. My son Alex is 8 years old.",
   'timestamp': '2026-03-09T17:23:51.656817'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information! Alex is 8 years old, so he's under 16, which is good for the initial age requirement.\n\nNow I need to ask you some questions about your relationship to Alex and your circumstances:\n\n**Do you live with Alex, or does he live with someone else?**",
   'timestamp': '2026-03-09T17:23:54.664906'},
  {'author': 'actor',
   'text': 'Yes, Alex lives with me.',
   'timestamp': '2026-03-09T17:23:56.303670'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Great, thank you. Now I need to understand a bit more about your responsibility for Alex:\n\n**Are you responsible for Alex? This means you're the one who looks after him and pays towards the costs of raising him (like food, clothing, and other expenses)?**",
   'timestamp': '2026-03-09T17:23:58.863799'},
  {'author': 'actor',
   'text': "Yes, I'm responsible for Alex. I look after him and pay for all his needs - food, clothing, everything he needs.",
   'timestamp': '2026-03-09T17:24:00.708415'},
  {'author': 'child_benefit_eligibility_agent',
   'text': 'Excellent, thank you. Now I need to ask about your residency status:\n\n**Are you living in the UK?**',
   'timestamp': '2026-03-09T17:24:02.447954'},
  {'author': 'actor',
   'text': "No, I'm not living in the UK at the moment. I'm living abroad.",
   'timestamp': '2026-03-09T17:24:04.292242'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for letting me know. This is an important factor for Child Benefit eligibility.\n\n**Where are you currently living, and are you working abroad?** Also, **is your absence from the UK temporary or permanent?**\n\nThe reason I ask is that there are some circumstances where you can still claim Child Benefit even if you're temporarily abroad - for example, if you're a Crown servant (like a diplomat or member of the armed forces) or working for certain international organizations. However, generally, you need to be living in the UK to claim Child Benefit.",
   'timestamp': '2026-03-09T17:24:07.921512'},
  {'author': 'actor',
   'text': "I'm living abroad, and it's not a temporary situation. I'm not a Crown servant or working for the armed forces or anything like that - just living overseas.",
   'timestamp': '2026-03-09T17:24:10.040819'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for clarifying that information.\n\nBased on what you've told me, I now have enough information to assess your eligibility for Child Benefit for Alex.\n\nLet me provide you with my assessment:\n\n**Unfortunately, you are not eligible for Child Benefit for Alex.** \n\nThe main reason is that one of the key eligibility requirements for Child Benefit is that you must be living in the UK. Since you've confirmed that you're living abroad permanently and you're not in one of the special categories (such as Crown servants, members of the armed forces, or working for certain international organizations), you do not meet the residency requirement for Child Benefit.\n\nWhile you meet the other criteria - Alex is under 16, he lives with you, and you're responsible for him - the UK residency requirement is essential for eligibility.\n\nIf your circumstances change and you move back to the UK in the future, you would be able to apply for Child Benefit at that time, provided you continue to meet the other eligibility criteria.\n\nIs there anything else you'd like to know about Child Benefit?",
   'timestamp': '2026-03-09T17:24:15.249487'}],
 [{'author': 'child_benefit_eligibility_agent',
   'text': "Hello! I'd be happy to help you determine if you're eligible for Child Benefit.\n\nTo assess your eligibility, I'll need to ask you some questions about your circumstances and the children in your care.\n\nLet me start with the first question: **Do you have a child or children that you're responsible for?** If yes, could you please tell me how many children you're asking about?",
   'timestamp': '2026-03-09T17:46:39.364631'},
  {'author': 'actor',
   'text': "Hello! Yes, I do. I'm asking about my son Alex - he's 17 years old and lives with me at home.",
   'timestamp': '2026-03-09T17:46:41.183819'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information. I'm assessing eligibility for your son Alex, who is 17 years old and lives with you.\n\nSince Alex is 17, I need to ask: **Is Alex currently in approved education or training?** \n\nThis would include things like:\n- A-levels or similar qualifications\n- T-levels\n- Scottish Highers\n- NVQs up to level 3\n- Home education (if started before they turned 16)\n- Certain training courses",
   'timestamp': '2026-03-09T17:46:44.688356'},
  {'author': 'actor',
   'text': 'Yes, he is. Alex is in sixth form doing his A-levels at the moment.',
   'timestamp': '2026-03-09T17:46:46.532178'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "That's helpful, thank you. Since Alex is doing A-levels in sixth form, that counts as approved education.\n\nNow I need to ask: **When did Alex turn 16, or when will he turn 16?** (I need to know the specific date if possible, or at least the month and year)\n\nThis is important because there are specific rules about how long Child Benefit can continue after a child turns 16 while they're in education.",
   'timestamp': '2026-03-09T17:46:49.808677'},
  {'author': 'actor',
   'text': "He turned 16 last year. He's 17 now, so he's been in sixth form for a while already.",
   'timestamp': '2026-03-09T17:46:51.957625'},
  {'author': 'child_benefit_eligibility_agent',
   'text': 'Thank you. To be more specific, could you tell me **which month and year Alex turned 16?** \n\nAlso, I need to know: **Do you know when his current education or training is scheduled to end?** (For example, when does his A-level course finish?)\n\nThese dates are important because Child Benefit for 16-19 year olds in education has specific time limits.',
   'timestamp': '2026-03-09T17:46:54.927769'},
  {'author': 'actor',
   'text': "I don't have the exact dates off the top of my head right now - I'd need to check his birth certificate for the precise date he turned 16, and the college would have his course end date. Is that information absolutely necessary for you to tell me if I'm eligible in general?",
   'timestamp': '2026-03-09T17:46:57.896749'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "That's a fair question. Let me explain what I can tell you at this stage:\n\n**In general terms**, you can continue to get Child Benefit for a child aged 16-19 if they're in approved full-time education or training (which Alex is, doing A-levels). However, the benefit stops on specific dates that depend on when they turned 16 and when their course ends.\n\nBefore I can give you a definitive answer about your eligibility, I do need to ask a few more general questions:\n\n1. **Are you (or your partner if you have one) responsible for Alex?** This means you're supporting him financially and he lives with you.\n\n2. **Do you or your partner currently live in the UK?**\n\nLet me check these basic eligibility criteria first, and then we can discuss whether the specific dates are needed for a final determination.",
   'timestamp': '2026-03-09T17:47:03.013259'},
  {'author': 'actor',
   'text': "Yes, I'm responsible for Alex - he lives with me and I support him. And yes, I live in the UK, in Leeds actually.",
   'timestamp': '2026-03-09T17:47:05.679346'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for confirming that. And just to check: **Do you have a partner, and if so, are they also living in the UK?**\n\nAlso, I need to ask: **Is anyone else claiming Child Benefit for Alex, or is anyone else claiming he lives with them?** (For example, Alex's other parent, if applicable)",
   'timestamp': '2026-03-09T17:47:08.342258'},
  {'author': 'actor',
   'text': "No, I don't have a partner - it's just me and Alex. And no, nobody else is claiming Child Benefit for him. It's just the two of us at home.",
   'timestamp': '2026-03-09T17:47:10.051620'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for providing all that information. Let me summarize what you've told me about your situation:\n\n- You're responsible for Alex (17 years old)\n- He lives with you in Leeds\n- He's in sixth form doing A-levels (approved education)\n- No one else is claiming Child Benefit for him\n- You're living in the UK\n- You don't have a partner\n\n**Based on the eligibility rules, you appear to be eligible for Child Benefit for Alex.**\n\nThe key criteria are met:\n- You're responsible for a child under 20\n- The child is in approved full-time education (A-levels)\n- You live in the UK\n- No one else is claiming for him\n\n**Important notes:**\n- Child Benefit normally stops when a young person turns 20, or when they leave approved education or training (whichever comes first)\n- It also stops on 31 August (or the Monday after the last Tuesday in May/June if they leave education then) following their 16th birthday if they're not continuing in education\n- Since Alex is 17 and currently in A-levels, your benefit should continue until he finishes his course or turns 20\n\nWould you like any information about how to claim, or do you have any other questions?",
   'timestamp': '2026-03-09T17:47:16.329912'},
  {'author': 'actor',
   'text': "That's brilliant, thank you so much for explaining everything! That's really helpful to know I'm eligible. I appreciate you walking me through all of that.",
   'timestamp': '2026-03-09T17:47:20.425188'}],
 [{'author': 'child_benefit_eligibility_agent',
   'text': "Hello! I'd be happy to help you determine if you're eligible for Child Benefit. Let me start by asking you a few questions.\n\nFirst, do you have a child or children that you're responsible for?",
   'timestamp': '2026-03-09T19:23:08.981279'},
  {'author': 'actor',
   'text': "Yes, I do! I have one child, Alex, who's 13 years old and lives with me.",
   'timestamp': '2026-03-09T19:23:10.729721'},
  {'author': 'child_benefit_eligibility_agent',
   'text': 'Thank you for that information! Let me ask you some questions to assess your eligibility for Child Benefit for Alex.\n\nFirst, are you or your partner responsible for Alex? By this I mean, do you pay for things like their food, clothing, or other living costs?',
   'timestamp': '2026-03-09T19:23:13.598909'},
  {'author': 'actor',
   'text': "Well, actually, my ex-partner is the one who mainly handles those things. They live together and my ex takes care of Alex's day-to-day expenses.",
   'timestamp': '2026-03-09T19:23:15.747669'},
  {'author': 'child_benefit_eligibility_agent',
   'text': 'Thank you for clarifying that. This is an important point - Child Benefit is generally paid to the person the child lives with and who is responsible for their day-to-day care and expenses.\n\nJust to confirm: does Alex live with your ex-partner full-time, or does Alex split their time between you and your ex-partner? And if Alex does spend time living with you, roughly how much of the time would that be?',
   'timestamp': '2026-03-09T19:23:18.818580'},
  {'author': 'actor',
   'text': "Alex lives with my ex-partner full-time. They don't split time between us - Alex stays with them.",
   'timestamp': '2026-03-09T19:23:20.639658'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information. Based on what you've told me, since Alex lives full-time with your ex-partner and your ex-partner is responsible for Alex's day-to-day expenses and care, **your ex-partner would be the person eligible to claim Child Benefit for Alex, not you**.\n\nChild Benefit is paid to the person who:\n- The child lives with, and\n- Who is responsible for the child (meaning they pay for things like food, clothing, and other living costs)\n\nSince your ex-partner meets both of these criteria, they would be the eligible claimant.\n\nHowever, if your circumstances change in the future - for example, if Alex comes to live with you and you become responsible for their care - you could then apply for Child Benefit at that time.\n\nIs there anything else you'd like to know about Child Benefit?",
   'timestamp': '2026-03-09T19:23:24.451287'}],
 [{'author': 'child_benefit_eligibility_agent',
   'text': "Hello! I'd be happy to help you determine if you're eligible for Child Benefit in the UK.\n\nTo assess your eligibility, I'll need to ask you some questions about your circumstances. Let me start with the basics:\n\n**Do you have any children that you're responsible for?** If yes, could you please tell me:\n- How many children you have\n- Their names (or just first names)\n- Their ages\n\nThis will help me understand your situation and guide you through the eligibility assessment.",
   'timestamp': '2026-03-09T18:17:30.658109'},
  {'author': 'actor',
   'text': 'Hello! Yes, I do have a child. I have one child - Alex, who is 19 years old and lives with me at home.',
   'timestamp': '2026-03-09T18:17:32.616418'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information! I can see that you have one child, Alex, who is 19 years old and lives with you.\n\nSince Alex is 19, I need to ask some additional questions to determine eligibility, as Child Benefit typically covers children under 16, or under 20 if they're in approved education or training.\n\n**Is Alex currently in approved education or training?** For example:\n- Full-time non-advanced education (such as studying for A-levels, Scottish Highers, or similar qualifications)\n- Approved training courses (like certain vocational training programs)\n\nPlease note that university or other advanced education courses do not count as approved education for Child Benefit purposes.",
   'timestamp': '2026-03-09T18:17:36.712556'},
  {'author': 'actor',
   'text': "Yes, Alex is in approved education - he's studying for his A-levels at the local sixth form college.",
   'timestamp': '2026-03-09T18:17:38.378035'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information! That's helpful to know.\n\nSince Alex is 19 and studying for A-levels, which is approved education, there are a few more questions I need to ask:\n\n**When did Alex turn 19?** (Please provide the month and year, or how many months ago)\n\nThis is important because Child Benefit can continue until the 31st of August following a young person's 19th birthday, as long as they remain in approved education.",
   'timestamp': '2026-03-09T18:17:41.473507'},
  {'author': 'actor',
   'text': 'He turned 19 about 5 months ago, so that would have been back in October.',
   'timestamp': '2026-03-09T18:17:43.313598'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for that information. So Alex turned 19 in October, which means he's currently 19 and studying for his A-levels.\n\nI need to clarify one more important detail:\n\n**When is Alex expected to finish his A-level course?** Specifically:\n- Is he finishing this academic year (in summer, around June/July)?\n- Or is he continuing into another academic year beyond this August?\n\nThis matters because Child Benefit continues for young people in approved education only until the 31st of August following their 19th birthday. Since Alex turned 19 in October (a few months ago), the cutoff date for him would be 31st August of this year.",
   'timestamp': '2026-03-09T18:17:47.026186'},
  {'author': 'actor',
   'text': "He's continuing beyond this August - he won't finish his A-levels until next summer.",
   'timestamp': '2026-03-09T18:17:48.693340'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for providing all that information. Let me make sure I understand your situation correctly:\n\n- Alex is 19 years old (turned 19 in October)\n- He's studying for A-levels at sixth form college (approved education)\n- He lives with you\n- He won't finish his A-levels until next summer (beyond August of this year)\n\nBefore I give you my final assessment, I need to ask one more question:\n\n**Are you the person responsible for Alex?** In other words, do you have parental responsibility for him and are you the main person caring for him?",
   'timestamp': '2026-03-09T18:17:51.993895'},
  {'author': 'actor',
   'text': "Yes, I am responsible for Alex. I'm his parent and he lives with me at home.",
   'timestamp': '2026-03-09T18:17:53.813242'},
  {'author': 'child_benefit_eligibility_agent',
   'text': "Thank you for confirming all of that information. I now have enough details to assess your eligibility for Child Benefit for Alex.\n\nLet me provide you with my assessment:\n\n**Unfortunately, you would not be eligible for Child Benefit for Alex.**\n\nHere's why: While Alex is in approved education (A-levels), which normally allows Child Benefit to continue beyond age 16, there is an age limit. Child Benefit only continues for young people in approved education until **31st August following their 19th birthday**.\n\nSince Alex turned 19 in October (which was about 5 months ago), the 31st August deadline has already passed - it would have been the August *before* he turned 19. This means Child Benefit eligibility ended on 31st August before his 19th birthday in October.\n\nEven though Alex is still studying for his A-levels and living with you, he has passed the maximum age limit for Child Benefit eligibility.\n\nI'm sorry this isn't the outcome you were hoping for, but I hope this explanation helps clarify the situation.\n\nIs there anything else you'd like to know about Child Benefit?",
   'timestamp': '2026-03-09T18:17:58.615003'},
  {'author': 'actor',
   'text': "Oh, I see. That's disappointing, but thank you for explaining it clearly. Just to make sure I understand - so even though he's still in college doing his A-levels, because he's already past that August deadline after turning 19, I can't claim for him anymore?\n\nAlso, I should mention - he has been in hospital for a couple of months recently. Does that make any difference to the eligibility?",
   'timestamp': '2026-03-09T18:18:01.992478'},
  {'author': 'child_benefit_eligibility_agent',

In [10]:
no_answer_df["meta.permutation"]

0     2
0    40
0    99
0    85
0    82
0    34
0    86
0    67
0    53
Name: meta.permutation, dtype: int64

In [11]:
df["tool_activity"].to_list()

[[{'timestamp': '2026-03-09T17:51:06.014920',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex', 'Blake', 'Charlie'],
    'is_eligible_list': [True, True, True],
    'reasonings': ['Alex is 5 years old, which is under 16. Alex lives with you in the UK, you are the parent responsible for their day-to-day care, and no one else is claiming Child Benefit for Alex. Alex is not in local authority care or long-term hospital/residential care. Therefore, you meet all the eligibility criteria for Child Benefit for Alex.',
     "Blake is 17 years old. While Blake is over 16, children can qualify for Child Benefit up to age 20 if they are in approved education or training. Although Blake's education status wasn't explicitly confirmed, as a 17-year-old living at home with their parent who is responsible for their care, and with no one else claiming for them and not in care, Blake qualifies for Child Benefit eligibility assessment. Blake lives with you in the UK, you are the parent responsible for their day-to-day care, and no one else is claiming Child Benefit for Blake. Blake is not in local authority care or long-term hospital/residential care. Therefore, you meet the eligibility criteria for Child Benefit for Blake.",
     'Charlie is 19 years old and is in approved education (studying for A-levels at college). Children aged 16-19 can qualify for Child Benefit if they are in approved full-time non-advanced education or approved training. Charlie lives with you in the UK, you are the parent responsible for their day-to-day care, and no one else is claiming Child Benefit for Charlie. Charlie is not in local authority care or long-term hospital/residential care. Therefore, you meet all the eligibility criteria for Child Benefit for Charlie.'],
    'overall_reasoning': 'You are eligible to claim Child Benefit for all three of your children: Alex (5), Blake (17), and Charlie (19). Alex qualifies as they are under 16. Blake qualifies as they are under 20. Charlie qualifies because although they are 19, they are still in approved education (studying for A-levels). You live in the UK, are the parent responsible for all three children who live with you, no one else is claiming for them, and none are in care. You meet all the eligibility requirements.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:24:44.637305',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex', 'Blake'],
    'is_eligible_list': [False, False],
    'reasonings': ['Alex is 5 years old and lives with the claimant, which would normally meet the basic age requirement for Child Benefit (under 16, or under 20 if in approved education or training). However, the claimant is living abroad and is not receiving any UK state pension or benefits, not working for a UK-based employer abroad, and has no Crown service or official UK government connection. Under UK Child Benefit rules, you must normally live in the UK to claim Child Benefit. Therefore, Alex does not qualify for Child Benefit under these circumstances.',
     'Blake is 10 years old and lives with the claimant, which would normally meet the basic age requirement for Child Benefit (under 16, or under 20 if in approved education or training). However, the claimant is living abroad and is not receiving any UK state pension or benefits, not working for a UK-based employer abroad, and has no Crown service or official UK government connection. Under UK Child Benefit rules, you must normally live in the UK to claim Child Benefit. Therefore, Blake does not qualify for Child Benefit under these circumstances.'],
    'overall_reasoning': 'The claimant has two children, Alex (5) and Blake (10), who both live with them. While both children meet the age requirements for Child Benefit, the family is living abroad with no UK benefits, UK employment connections, or Crown service ties. The fundamental residency requirement for UK Child Benefit is not met, making the claimant ineligible to claim Child Benefit for either child.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T19:21:36.930717',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex', 'Blake'],
    'is_eligible_list': [True, True],
    'reasonings': ['Alex is 9 years old, which is under 16, so meets the age requirement. Alex lives with you, you are responsible for Alex and provide for their upbringing, no one else is claiming Child Benefit for Alex, and you live in the UK with the right to claim benefits. Alex attends regular primary school which does not affect eligibility. Therefore, you are eligible to claim Child Benefit for Alex.',
     'Blake is 5 years old, which is under 16, so meets the age requirement. Blake lives with you, you are responsible for Blake and provide for their upbringing, no one else is claiming Child Benefit for Blake, and you live in the UK with the right to claim benefits. Blake attends regular primary school which does not affect eligibility. Therefore, you are eligible to claim Child Benefit for Blake.'],
    'overall_reasoning': 'The claimant is responsible for two children, Alex (age 9) and Blake (age 5), who both live with them in the UK. Both children are under 16 years old, the claimant provides for their upbringing, no one else is claiming Child Benefit for either child, and the claimant has the right to live and claim benefits in the UK. All eligibility criteria are met for both children.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:33:41.300594',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ["Alex is 8 years old, which is under 16, so meets the age requirement. However, Alex does not live with the claimant - Alex lives full-time with their other parent. The claimant provides only financial support (money for clothes, school expenses, etc.) but Alex does not stay with the claimant at any time. Under UK Child Benefit rules, when a child doesn't live with you, you can only claim if you contribute to the cost of providing for the child AND the child lives with you at least part of the time. Since Alex never stays with the claimant and the support is purely financial, the claimant does not meet the 'living with' requirement. Only one person can claim Child Benefit for a child, and it should be the person the child lives with - in this case, Alex's other parent."],
    'overall_reasoning': 'The claimant has one child, Alex (age 8), who lives full-time with their other parent. The claimant provides financial support but Alex does not stay with them. Under Child Benefit rules, the benefit is paid to the person the child lives with. Since Alex does not live with the claimant even part-time, the claimant is not eligible. The other parent who Alex lives with would be the eligible person to claim.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T18:09:00.374374',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex', 'Blake'],
    'is_eligible_list': [True, True],
    'reasonings': ['Alex is 13 years old (under 16), in full-time secondary school education, lives with you (the claimant), and has not started living with a partner or has a child of their own. You are a UK citizen living in the UK (Manchester). You meet the responsibility test as Alex normally lives with you. Therefore, you are eligible to claim Child Benefit for Alex.',
     "Blake is 15 years old (under 16), in full-time secondary school education, has not started living with a partner or has a child of their own, and you are a UK citizen living in the UK. Although Blake does not live with you, you contribute approximately £26 per week towards Blake's upkeep, which meets the financial contribution threshold (Child Benefit rate for one child is currently around £25 per week). You meet the responsibility test through financial contribution at least equal to the Child Benefit amount. As far as you know, nobody else is claiming Child Benefit for Blake, which means only one person would be claiming (priority rules apply if someone else also claims, but that's not the case here). Therefore, you are eligible to claim Child Benefit for Blake."],
    'overall_reasoning': "The claimant is a UK citizen living in Manchester with two children: Alex (13) and Blake (15). Both children are under 16, in full-time education, and have not started living with partners or have children of their own. Alex lives with the claimant, clearly meeting the responsibility test. Blake does not live with the claimant, but the claimant contributes approximately £26 per week towards Blake's upkeep, which meets the threshold of contributing at least the equivalent of Child Benefit. No one else is claiming for Blake. Neither the claimant nor their partner earns over £60,000, so the High Income Child Benefit Charge does not apply. The claimant is eligible to claim Child Benefit for both children."},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:30:40.994810',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ['Alex is 18 years old and not in approved education or training. Under UK Child Benefit rules, you can claim Child Benefit until a child turns 16, or up until they turn 20 if they remain in approved education or training (such as A-levels, Scottish Highers, or approved training programs, but not university). Since Alex is 18 and not in approved education or training, they do not meet the age and education requirements for Child Benefit eligibility.'],
    'overall_reasoning': 'The claimant has one child, Alex, who is 18 years old and not currently in approved education or training. As Alex exceeds the age limit for Child Benefit (16, or 20 if in approved education/training) and is not in qualifying education, the claimant is not eligible for Child Benefit.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T19:19:07.518141',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [True],
    'reasonings': ['Alex is 9 years old (under 16), lives with the claimant in the UK, the claimant is a British citizen with the right to reside in the UK, no one else is claiming Child Benefit for Alex, and Alex is living at home attending primary school with no special circumstances such as being in hospital or local authority care. All eligibility criteria are met.'],
    'overall_reasoning': 'The claimant is a British citizen living in Manchester with their 9-year-old child Alex. Alex lives with them, attends primary school normally, and no one else is claiming Child Benefit for Alex. All eligibility requirements for Child Benefit are satisfied.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:49:11.245335',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex', 'Blake'],
    'is_eligible_list': [True, True],
    'reasonings': ['Alex is 5 years old (under 16), lives with the claimant in the UK, and the claimant is responsible for Alex by paying for their food, clothes, and other costs. Alex meets all the eligibility criteria for Child Benefit.',
     'Blake is 10 years old (under 16), lives with the claimant in the UK, and the claimant is responsible for Blake by paying for their food, clothes, and other costs. Blake meets all the eligibility criteria for Child Benefit.'],
    'overall_reasoning': 'The claimant is responsible for two children, Alex (5) and Blake (10), who both live with them full-time in the UK. Both children are under 16 years old and are not in care or hospital. The claimant pays for all their living costs including food, clothes, and school items. The claimant meets all the eligibility requirements for Child Benefit for both children.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:26:33.797179',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [True],
    'reasonings': ['Alex is 16 years old and studying for A-levels at college, which qualifies as approved education. Under UK Child Benefit rules, you can claim Child Benefit for 16 and 17-year-olds if they are in approved education or training. Alex lives with you full-time, you are responsible for their care, and no one else is claiming Child Benefit for them. You normally live in the UK and are not subject to immigration control. All eligibility criteria are met for Alex.'],
    'overall_reasoning': 'The claimant is eligible for Child Benefit for their 16-year-old child Alex. The claimant is responsible for Alex who lives with them in the UK, Alex is in approved education (A-levels), and there are no immigration or competing claim issues. All eligibility requirements are satisfied.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:37:04.381659',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [True],
    'reasonings': ['Alex is 8 years old, which is under 16 years old, meeting the age requirement for Child Benefit. Alex lives with the claimant who is responsible for his day-to-day care, including providing food, clothing, and looking after his general needs. The claimant lives in the UK and is a UK citizen, satisfying the residency and immigration status requirements. No one else is currently claiming Child Benefit for Alex. Therefore, all eligibility criteria are met for Alex.'],
    'overall_reasoning': "The claimant is a UK citizen living in the UK with their 8-year-old son Alex. The claimant is responsible for Alex's day-to-day care, Alex lives with them, and no one else is claiming Child Benefit for Alex. All eligibility criteria under UK Child Benefit rules are satisfied."},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:46:33.877134',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ["Alex is 17 years old and turned 16 over a year ago. Child Benefit automatically stops on 31st August following a child's 16th birthday unless the child continues in approved education or training. Alex is currently in a paid apprenticeship. For children aged 16-19, Child Benefit only continues if they are in approved unpaid education or training (up to 20 hours per week) or full-time non-advanced education. Paid apprenticeships count as employment and do not qualify as approved education or training for Child Benefit purposes. Therefore, the claimant is not eligible for Child Benefit for Alex."],
    'overall_reasoning': 'The claimant has one child, Alex, who is 17 years old and in a paid apprenticeship. As Alex turned 16 over a year ago and is now in paid employment (apprenticeship), which does not qualify as approved education or training, Child Benefit eligibility has ended.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T18:12:23.472529',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ['Alex is 6 years old, which is under 16 and would normally meet the age requirement. However, the claimant does not live in the UK and does not fall under any of the exceptions that allow people living abroad to claim Child Benefit (not a Crown servant, not working for an international organization with UK agreements, and not living in an EEA country or Switzerland). The residency requirement is a fundamental eligibility criterion for Child Benefit, and without meeting this requirement, the claimant cannot be eligible for Child Benefit for Alex.'],
    'overall_reasoning': 'The claimant is not eligible for Child Benefit because they do not meet the UK residency requirement. While their child Alex meets the age criteria (being 6 years old), the claimant lives abroad and does not qualify for any of the limited exceptions that would allow them to claim Child Benefit while living outside the UK.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:29:21.466992',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ['Alex is 17 years old and not in approved education or training. Under UK Child Benefit rules, for young people aged 16-19, Child Benefit can only be claimed if they are in approved education or training. Since Alex has left school and is not currently studying or in any training program, the claimant is not eligible for Child Benefit for Alex.'],
    'overall_reasoning': 'The claimant has one child, Alex, aged 17, who is not in education or training. Child Benefit eligibility for 16-17 year olds requires them to be in approved education or training, which Alex is not. Therefore, the claimant is not eligible for Child Benefit.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:51:25.776319',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],
    'reasonings': ['Alex is 18 years old and not in approved education or training. According to UK Child Benefit rules, you can claim Child Benefit until a child turns 16, or until they turn 20 if they stay in approved education or training. Since Alex is over 16 (he is 18) and is not in approved education or training - he is working full-time instead - he does not meet the eligibility criteria for Child Benefit.'],
    'overall_reasoning': 'The claimant has one child, Alex, who is 18 years old and working full-time. He is not in approved education or training. Child Benefit eligibility ends at age 16 unless the child continues in approved education or training (up to age 20). Since Alex does not meet these criteria, the claimant is not eligible for Child Benefit.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:24:17.091716',
   'tool_name': 'exit_loop',
   'arguments': {},
   'author': 'actor'}],
 [{'timestamp': '2026-03-09T19:22:09.020473',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [True],
    'reasonings': ['Alex is 6 years old, which is under 16, meeting the age requirement for Child Benefit. You are responsible for Alex, meaning you provide for their care and upbringing including food, clothing, and housing. Alex lives with you in the UK, and you usually live in the UK without being subject to immigration control. Alex is not in hospital or local authority care. No one else is claiming Child Benefit for Alex. All eligibility criteria are met.'],
    'overall_reasoning': 'The claimant meets all the eligibility requirements for Child Benefit for their 6-year-old child Alex. They are responsible for the child who lives with them in the UK, they usually live in the UK, are not subject to immigration control, and no one else is claiming for this child.'},
   'author': 'child_benefit_eligibility_agent'}],
 [{'timestamp': '2026-03-09T17:34:50.648555',
   'tool_name': 'eligibility_judgement_outcome',
   'arguments': {'child_names': ['Alex'],
    'is_eligible_list': [False],